### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by HarshKhilawala** [HarshKhilawala/Text-Recognition-and-Translation#2]
## Updating Readme.md file

**Comment by tapish2000** [comment]
If you want to have a Readme.md file, you can assign the issue to me. I will do it.

**Comment by HarshKhilawala** [comment]
Ok @tapish2000  You can start working on that

**Comment by HarshKhilawala** [comment]
@tapish2000 When are you going to do that ?

**Comment by tapish2000** [comment]
Can I create the pull request on 1st October?

**Comment by tapish2000** [comment]
Hey! Can I get a basic info on what is the project and how it works?

**Comment by HarshKhilawala** [comment]
Project is able to detect the number plate by sorting out the contours and after it is passed through tesseract OCR to extract the Text from the number plate.@tapish2000 .

Also , Make sure you get the pull request on 1st October after which we can't wait and hold our work. So get the work done before 1st October and then you just need to create PR on that day

**Comment by tapish2000** [comment]
No problem dude, I am on it. But you have used your system's path of various files and directories in many places in the program hardcoded. You should've made a different file for all the paths and import that file anywhere the path is needed. It is harder to track those files with hardcoded paths unless you help me out.

Like this:
![image](https://user-images.githubusercontent.com/44476667/94395671-ce61fc80-017d-11eb-8756-4a5a2159d915.png)

**Comment by HarshKhilawala** [comment]
@tapish2000 You are not required to write everything for this project and only need to write the Project Overview and the tools and libraries used. If you are facing problem let me know, I will take over the work and you can work on other thing if in case you want to get your PR counted for Hacktober Fest. We won't mind

**Comment by HarshKhilawala** [comment]
Maybe I can assign you to different issue for Hacktober Fest

**Comment by tapish2000** [comment]
@HarshKhilawala To know the Project Overview only, I was trying to run the project once, to get to know how it works so as to write in the Readme.md
Or you can tell me directly all these things, maybe we can have a talk if you want and you tell me a little about what should be written and I will make the Readme.
I can see the tools and libraries used by you in the folders you created. That is not a problem. I can't much about the Project without running it. That's why I was trying to do that.

**Comment by tapish2000** [comment]
I am fine with making Readme files, just that I should have some input in my mind. Help me in this.

**Comment by HarshKhilawala** [comment]
@tapish2000 Just mention out there that we are also looking for collaboration with App Developers for integrating our Models into Applications.

**Comment by tapish2000** [comment]
This is what I wrote till now. I just have one thing to write in Upcoming Features as you mentioned. Review this and let me know about more changes.
![image](https://user-images.githubusercontent.com/44476667/94728559-0c2d7380-037e-11eb-921c-a2a3c38d0440.png)

I will create the pull request today itself. **My first priority is this work** dude.

**Comment by HarshKhilawala** [comment]
@tapish2000 Nice Work! This is enough for the time being until we start working on the Translation Part. You can continue to create a pull request now. Thanks

**Comment by HarshKhilawala** [comment]
@tapish2000 Your PR has been merged! Thanks for your contribution towards our  project !
